name: lake-m3
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.5.5=ha0b305a_0
  - packaging=25.0=py312hca03da5_1
  - pip=26.0.1=pyhc872135_0
  - python=3.12.11=h421de30_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.46.3=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.5
      - numpy==2.2.6
      - pandas==2.3.1
      - pillow==12.1.1
      - pyparsing==3.3.2
      - pytz==2025.2
      - scipy==1.16.1
      - seaborn==0.13.2
      - tqdm==4.67.1
      - tzdata==2025.3
prefix: /opt/miniconda3/envs/lake-m3
