name: aem-py312
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - applaunchservices=0.3.0=py312hecd8cb5_0
  - appnope=0.1.4=py312hecd8cb5_0
  - arrow=1.3.0=py312hecd8cb5_0
  - asttokens=3.0.0=py312hecd8cb5_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - bcrypt=4.3.0=py312h83de92b_0
  - beautifulsoup4=4.13.4=py312hecd8cb5_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=25.1.0=py312hecd8cb5_0
  - bleach=6.2.0=py312hecd8cb5_0
  - brotlicffi=1.0.9.2=py312h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2025.2.25=hecd8cb5_0
  - cffi=1.17.1=py312h9205ec4_1
  - click=8.2.1=py312hecd8cb5_0
  - cloudpickle=3.1.1=py312hecd8cb5_0
  - cookiecutter=2.6.0=py312hecd8cb5_1
  - cyrus-sasl=2.1.28=hd1e62a0_3
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py312hecd8cb5_0
  - docutils=0.21.2=py312hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - gettext=0.21.0=h4e8c18a_2
  - glib=2.84.2=h918fcf5_0
  - glib-tools=2.84.2=h918fcf5_0
  - gst-plugins-base=1.14.1=hcec6c5f_1
  - gstreamer=1.14.1=h6c40b1e_1
  - icu=73.1=hcec6c5f_0
  - imagesize=1.4.1=py312hecd8cb5_0
  - inflection=0.5.1=py312hecd8cb5_1
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - isort=6.0.1=py312hecd8cb5_0
  - jedi=0.19.2=py312hecd8cb5_0
  - jinja2=3.1.6=py312hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - jsonschema=4.25.0=py312hecd8cb5_0
  - jupyter_client=8.6.3=py312hecd8cb5_0
  - jupyter_core=5.8.1=py312hecd8cb5_0
  - jupyterlab_pygments=0.3.0=py312hecd8cb5_0
  - keyring=25.6.0=py312hecd8cb5_0
  - krb5=1.20.1=h428f121_1
  - libabseil=20250127.0=cxx17_h548131f_0
  - libclang=14.0.6=default_h182e8cd_2
  - libclang13=14.0.6=default_h9f4243d_2
  - libcurl=8.14.1=h1448931_1
  - libcxx=17.0.6=hf547dac_4
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libffi=3.4.4=hecd8cb5_1
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libkrb5=1.21.3=h54be378_3
  - libllvm14=14.0.6=h26321d7_4
  - libnghttp2=1.57.0=h9beae6a_0
  - libpng=1.6.39=h6c40b1e_0
  - libpq=17.4=h40f65ae_2
  - libprotobuf=5.29.3=h66a43dd_1
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h23ab428_0
  - libssh2=1.11.1=h3a17b82_0
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=17.0.6=hdd4a2e0_0
  - lmdb=0.9.29=h23ab428_0
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=3.0.2=py312h46256e1_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mysql=8.4.0=h5364baf_2
  - nbclient=0.10.2=py312hecd8cb5_0
  - nbconvert=7.16.6=py312hecd8cb5_0
  - nbconvert-core=7.16.6=py312hecd8cb5_0
  - nbconvert-pandoc=7.16.6=py312hecd8cb5_0
  - nbformat=5.10.4=py312hecd8cb5_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=py312hecd8cb5_0
  - numpydoc=1.9.0=py312he13d532_0
  - openldap=2.6.4=h6e6fb41_0
  - openssl=3.0.17=hee2dfae_0
  - packaging=25.0=py312hecd8cb5_0
  - pandoc=2.12=hecd8cb5_3
  - parso=0.8.4=py312hecd8cb5_0
  - pathspec=0.12.1=py312hecd8cb5_0
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=py312hecd8cb5_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.1=pyhc872135_2
  - ply=3.11=py312hecd8cb5_1
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycodestyle=2.12.1=py312hecd8cb5_0
  - pydocstyle=6.3.0=py312hecd8cb5_0
  - pyflakes=3.2.0=py312hecd8cb5_0
  - pyjwt=2.10.1=py312hecd8cb5_0
  - pynacl=1.5.0=py312h46256e1_1
  - pysocks=1.7.1=py312hecd8cb5_0
  - python=3.12.11=he8d2d4c_0
  - python-dateutil=2.9.0post0=py312hecd8cb5_2
  - python-lsp-black=2.0.0=py312hecd8cb5_1
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.12.2=py312he13d532_0
  - python.app=3=py312h46256e1_2
  - pyuca=1.2=py312hecd8cb5_1
  - pyyaml=6.0.2=py312h46256e1_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qt-main=5.15.2=hf83fbd5_12
  - qt-webengine=5.15.9=h90a370e_7
  - qtconsole=5.6.1=py312hecd8cb5_1
  - readline=8.3=h49f2429_0
  - requests=2.32.4=py312hecd8cb5_0
  - roman-numerals-py=3.1.0=py312hecd8cb5_0
  - setuptools=78.1.1=py312hecd8cb5_0
  - sip=6.7.12=py312h6d0c2b6_1
  - six=1.17.0=py312hecd8cb5_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sphinx=8.2.3=py312h46256e1_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - spyder=6.0.7=py312hecd8cb5_1
  - spyder-kernels=3.0.5=py312he13d532_0
  - sqlite=3.50.2=hc8b0dd6_1
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.6.3=py312he13d532_1
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.4.0=py312hecd8cb5_0
  - tk=8.6.14=h0a12a5f_1
  - tomli=2.2.1=py312hecd8cb5_0
  - tornado=6.5.1=py312h46256e1_0
  - traitlets=5.14.3=py312hecd8cb5_0
  - ujson=5.10.0=py312h6d0c2b6_1
  - unidecode=1.3.8=py312hecd8cb5_0
  - urllib3=2.5.0=py312hecd8cb5_0
  - wcwidth=0.2.13=py312hecd8cb5_0
  - webencodings=0.5.1=py312hecd8cb5_2
  - wheel=0.45.1=py312hecd8cb5_0
  - wrapt=1.17.0=py312h46256e1_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.5=hcec6c5f_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - astroid==3.3.11
      - asyncssh==2.21.0
      - atomicwrites==1.4.1
      - attrs==25.3.0
      - babel==2.17.0
      - certifi==2025.8.3
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - comm==0.2.3
      - contourpy==1.3.3
      - cryptography==45.0.6
      - cycler==0.12.1
      - debugpy==1.8.15
      - decorator==5.2.1
      - diff-match-patch==20241021
      - dill==0.4.0
      - docstring-to-markdown==0.17
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flake8==7.1.2
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - ipykernel==6.30.1
      - ipython==8.37.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.2.1
      - jellyfish==1.2.0
      - joblib==1.5.1
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - networkx==3.5
      - numba==0.61.2
      - numpy==2.2.6
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - pillow==11.3.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygithub==2.7.0
      - pygments==2.19.2
      - pylint==3.3.7
      - pylint-venv==3.0.4
      - pyls-spyder==0.4.0
      - pyobjc-core==11.1
      - pyobjc-framework-cocoa==11.1
      - pyobjc-framework-coreservices==11.1
      - pyobjc-framework-fsevents==11.1
      - pyparsing==3.2.3
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.17
      - python-slugify==8.0.4
      - pytoolconfig==1.3.1
      - pytz==2025.2
      - pyzmq==27.0.1
      - qstylizer==0.2.4
      - qtawesome==1.4.0
      - qtpy==2.4.3
      - referencing==0.36.2
      - rich==14.1.0
      - rope==1.14.0
      - rpds-py==0.26.0
      - rtree==1.4.0
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - snowballstemmer==3.0.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - superqt==0.7.5
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tomlkit==0.13.3
      - torch==2.2.2
      - tqdm==4.67.1
      - types-python-dateutil==2.9.0.20250708
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - watchdog==6.0.0
      - whatthepatch==1.0.7
      - wurlitzer==3.1.1
      - yapf==0.43.0
      - yarl==1.20.1
      - zipp==3.23.0
